apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpapp
  labels:
    app: cpapp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpapp
      version: v1
  template:
    metadata:
      labels:
        app: cpapp
        version: v1
    spec:
      containers:
      - name: html5-apps-repo-cylindrical-employment
        image: docker-registry.{{CLUSTER_DOMAIN}}/cpapp
        imagePullPolicy: Always
        ports:
        - containerPort: 4004

    